// The colour themes a reader can choose from, and the pairs of colours that
// must stay legible in each. Every page's stylesheet and the contrast check
// read from here, so a colour can only change in one place. Without it the
// check would test a copy of the palette, not the one the pages use.

export const THEMES = {
  paper: {
    label: 'Paper',
    bg: '#FBF8F1',
    sunk: '#F3EDE1',
    surface: '#FFFFFF',
    ink: '#1F1B16',
    ink2: '#4A4338',
    rule: '#E3DACA',
    edge: '#857A68',
    link: '#1D4E89',
    visited: '#5A3A8E',
    hover: '#123764',
    onAccent: '#FFFFFF',
    focus: '#1F1B16',
    focusBg: '#FFE27A',
    focusInk: '#1F1B16',
    plainBg: '#F6ECD5',
    plainEdge: '#E2CFA3',
    plainLabel: '#6A4508',
    deepBg: '#EDF1F4',
    deepEdge: '#C6D0DA',
    deepLabel: '#2D4760',
    trueInk: '#1E5B38',
    falseInk: '#8A2E1C',
    sayInk: '#1D4E89',
    codeBg: '#F2ECE0',
    codeNote: '#4E473B',
    zebra: '#F7F2E8',
    select: '#FFE27A',
    selectInk: '#1F1B16',
  },
  white: {
    label: 'White',
    bg: '#FFFFFF',
    sunk: '#F3F4F6',
    surface: '#FFFFFF',
    ink: '#15171B',
    ink2: '#434954',
    rule: '#E1E4E8',
    edge: '#7A828E',
    link: '#0B4A96',
    visited: '#5B3690',
    hover: '#07336A',
    onAccent: '#FFFFFF',
    focus: '#15171B',
    focusBg: '#FFE27A',
    focusInk: '#15171B',
    plainBg: '#FFF3D4',
    plainEdge: '#EBD39A',
    plainLabel: '#684406',
    deepBg: '#EEF3F8',
    deepEdge: '#C5D1DE',
    deepLabel: '#284460',
    trueInk: '#1B5A36',
    falseInk: '#8A2B1A',
    sayInk: '#0B4A96',
    codeBg: '#F2F3F5',
    codeNote: '#464C57',
    zebra: '#F6F7F9',
    select: '#FFE27A',
    selectInk: '#15171B',
  },
  dark: {
    label: 'Dark',
    bg: '#1A1917',
    sunk: '#23211E',
    surface: '#22201D',
    ink: '#EFE9DE',
    ink2: '#C8C0B2',
    rule: '#3A3731',
    edge: '#8C8476',
    link: '#9EC5FF',
    visited: '#D4BAFF',
    hover: '#C6DCFF',
    onAccent: '#1A1917',
    focus: '#FFD166',
    focusBg: '#FFD166',
    focusInk: '#1A1917',
    plainBg: '#2C2619',
    plainEdge: '#57492A',
    plainLabel: '#F2C96B',
    deepBg: '#1D232A',
    deepEdge: '#3C4a58',
    deepLabel: '#A9C9EA',
    trueInk: '#94D8AC',
    falseInk: '#F5A995',
    sayInk: '#9EC5FF',
    codeBg: '#24221F',
    codeNote: '#BDB4A5',
    zebra: '#201F1C',
    select: '#3D3210',
    selectInk: '#EFE9DE',
  },
  contrast: {
    label: 'High contrast',
    bg: '#000000',
    sunk: '#000000',
    surface: '#000000',
    ink: '#FFFFFF',
    ink2: '#FFFFFF',
    rule: '#FFFFFF',
    edge: '#FFFFFF',
    link: '#FFFF00',
    visited: '#FFB8FF',
    hover: '#FFFFFF',
    onAccent: '#000000',
    focus: '#00FFFF',
    focusBg: '#00FFFF',
    focusInk: '#000000',
    plainBg: '#000000',
    plainEdge: '#FFFFFF',
    plainLabel: '#FFFFFF',
    deepBg: '#000000',
    deepEdge: '#FFFFFF',
    deepLabel: '#FFFFFF',
    trueInk: '#FFFFFF',
    falseInk: '#FFFFFF',
    sayInk: '#FFFFFF',
    codeBg: '#000000',
    codeNote: '#FFFFFF',
    zebra: '#000000',
    select: '#FFFF00',
    selectInk: '#000000',
  },
};

export const THEME_ORDER = ['paper', 'white', 'dark', 'contrast'];

// Text colours and the backgrounds each is drawn on. AAA asks 7:1 of all text
// here, including large text, so that nothing depends on a size exception.
export const TEXT_PAIRS = [
  ['ink', 'bg'],
  ['ink', 'sunk'],
  ['ink', 'surface'],
  ['ink', 'plainBg'],
  ['ink', 'deepBg'],
  ['ink', 'codeBg'],
  ['ink', 'zebra'],
  ['ink2', 'bg'],
  ['ink2', 'surface'],
  ['ink2', 'sunk'],
  ['ink2', 'zebra'],
  ['ink2', 'plainBg'],
  ['ink2', 'deepBg'],
  ['link', 'bg'],
  ['link', 'surface'],
  ['link', 'sunk'],
  ['link', 'plainBg'],
  ['link', 'deepBg'],
  ['link', 'zebra'],
  ['visited', 'bg'],
  ['visited', 'surface'],
  ['visited', 'sunk'],
  ['visited', 'plainBg'],
  ['visited', 'deepBg'],
  ['visited', 'zebra'],
  ['hover', 'bg'],
  ['hover', 'surface'],
  ['hover', 'sunk'],
  ['onAccent', 'link'],
  ['focusInk', 'focusBg'],
  ['plainLabel', 'plainBg'],
  ['deepLabel', 'deepBg'],
  ['trueInk', 'surface'],
  ['falseInk', 'surface'],
  ['sayInk', 'surface'],
  ['codeNote', 'codeBg'],
  ['selectInk', 'select'],
];

// Boundaries and indicators that must stand out from what surrounds them:
// 3:1 for component edges (1.4.11) and for the focus ring (2.4.13).
export const UI_PAIRS = [
  ['edge', 'bg'],
  ['edge', 'surface'],
  ['edge', 'sunk'],
  ['focus', 'bg'],
  ['focus', 'surface'],
  ['focus', 'sunk'],
  ['focus', 'plainBg'],
  ['focus', 'deepBg'],
  ['focus', 'codeBg'],
  ['link', 'bg'],
];

export function luminance(hex) {
  const n = hex.replace('#', '');
  const [r, g, b] = [0, 2, 4].map((i) => parseInt(n.slice(i, i + 2), 16) / 255);
  const lin = (c) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
  return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b);
}

export function contrast(a, b) {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
}
